version: '3.9'

services:
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

  backend:
    build: ./backend
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      SECRET_KEY: "123123"
    ports:
      - 8081:8081
    restart: always

  frontend:
    build: ./frontend
    ports:
      - 8080:80

volumes:
  mongodb_data: