FROM docker.io/library/golang:1.20 AS build-env
WORKDIR /app
COPY . /app
RUN go mod tidy && go build -o backend .

FROM alpine
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
WORKDIR /app
COPY --from=build-env /app/backend /app
EXPOSE 8081
ENTRYPOINT ./backend
